default_platform(:mac)

CODESIGN_IDENTITY = "Developer ID Application: CHECK24 Vergleichsportal Ferienwohnungen GmbH".freeze
TEAM_ID = "L8NKS8SMU3".freeze
BUNDLE_IDENTIFIER = "de.check24.ferienwohnung.sequel-ace".freeze
PROVISION_PROFILE_NAME = "Sequel Ace Distribution".freeze
KEYCHAIN_PATH = "Signing/sequel-ace.keychain".freeze

platform :mac do
  desc "Build and sign macOS app for ad-hoc distribution"
  lane :build_and_sign_mac_app do | options |
    unlock_and_add_keychain(
        password: options[:keychain_password]
    )
    
    install_provisioning_profile(
        path: "Signing/Sequel_Ace_Distribution.provisionprofile"
    )
        
    update_code_signing_settings(
        use_automatic_signing: false,
        code_sign_identity: CODESIGN_IDENTITY,
        team_id: TEAM_ID,
        bundle_identifier: BUNDLE_IDENTIFIER,
        profile_name: PROVISION_PROFILE_NAME,
        targets: "Sequel Ace"
    )
    
    gym(
        clean: true,
        scheme: "Sequel Ace Release",
        configuration: "Distribution",
        export_method: "developer-id",
        export_options: {
            provisioningProfiles: {
                "de.check24.ferienwohnung.sequel-ace" => PROVISION_PROFILE_NAME,
            },
        },
        output_directory: "build",
    )
  end
end

private_lane :unlock_and_add_keychain do |options|
    unlock_keychain(
        path: KEYCHAIN_PATH,
        password: options[:password],
        add_to_search_list: :add,
        set_default: true
    )
end
